nodeLinker: pnp

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 9037148C-6DC5-4546-B456-47E5A8DA64AF
    npmRegistryServer: "https://npm.fontawesome.com/"

packageExtensions:
  "@nivo/bar@*":
    dependencies:
      prop-types: "*"
      react-dom: "*"
  "@nivo/colors@*":
    dependencies:
      prop-types: "*"
      react-dom: "*"
  "@nivo/core@*":
    dependencies:
      prop-types: "*"
      react-dom: "*"
  "@nivo/legends@*":
    dependencies:
      prop-types: "*"
      react-dom: "*"
  styled-components@*:
    dependencies:
      react-dom: "*"
      react-is: "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
